# Generated by Django 4.2.1 on 2023-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripción', models.TextField(blank=True)),
                ('precio', models.DateTimeField(auto_now_add=True)),
                ('fecha_registro', models.DateTimeField(null=True)),
                ('estatus', models.BooleanField(default=False)),
            ],
        ),
    ]
