# Generated by Django 4.2.1 on 2023-05-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
